[build]
builder = "NIXPACKS"

[deploy]
startCommand = "npm run start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[[services]]
name = "backend"
buildCommand = "cd backend && npm ci"
startCommand = "cd backend && npm start"

[[services.healthcheck]]
path = "/health"
interval = 30
timeout = 5
maxRetries = 3

[[services]]
name = "frontend"
buildCommand = "cd frontend && npm ci && npm run build"
startCommand = "cd frontend && npm run preview"

[[services]]
name = "discord-bot"
buildCommand = "cd discord-bot && npm ci"
startCommand = "cd discord-bot && npm start"